### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by rjrichards27** [rjrichards27/Predicing_House_Prices#3]
**Analysis:**
- [x] Compare final models [All on Sunday]
- [x] Train model for all data [Robert]
- [x] Train models for GA only, and CA only[Robert]
- [x] Using the model for GA only, Validate on GA and CA (remove state, county, and city) [Rachel]
- [x] Using the model for CA only, Validate on GA and CA (remove state, county, and city) [Himangshu]
- [x] Validate on All/GA/CA/Each Home type [Minjung]

**Video**
- [x] Presentation [Minjung and Rachel]
- [x] Methodology [Robert]

**Report:**
- [x] Abstract [Himangshu]
- [x] Intro and Motivation [Rachel]
- [x] Background [Rachel]
- [x] Data [Minjung]
- [x] Methods and Experiments [Robert]
- [x] Results [Minjung]
- [x] Conclusion [Himangshu]
